# Generated by Django 4.1 on 2023-03-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0011_alter_minute_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='Location',
            field=models.TextField(max_length=30),
        ),
    ]
