# Generated by Django 4.1 on 2023-03-07 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0013_alter_college_location_alter_school_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minute',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
