# Generated by Django 4.1 on 2023-03-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0014_alter_minute_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minute',
            name='Date',
        ),
    ]
