# Generated by Django 4.1 on 2023-03-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0015_remove_minute_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='Email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
    ]
