# Generated by Django 4.1 on 2023-03-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0016_college_email_school_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='Email',
            field=models.EmailField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='Email',
            field=models.EmailField(blank=True, default='', max_length=30, null=True),
        ),
    ]
