# Generated by Django 4.1 on 2023-03-08 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0020_alter_college_location_alter_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
